[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationLBFGSB = "22f7324a-a79d-40f2-bebe-3af60c77bd15"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
