project:
  type: website
  output-dir: _build
  execute-dir: project 
  render:
    - "*.qmd"
    - "examples/*.qmd"
    - "examples/*.jl"

manuscript:
  meca-bundle: true

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  custom:
    - kind: float # Callouts are treated as "floats" for cross-referencing purposes
      key: doc # This is your custom key, use it as part of your ID (e.g., #mycallout-example)
      reference-prefix: Doc # The text that will appear before the number in references (e.g., "Callout 1")
      
fig-format: png


website:
  title: "Corleone.jl"
  announcement: 
    dismissable: true
    content: "Corleone.jl documentation goes live!" 
    type: primary
    position: below-navbar
  search: 
    type: overlay
    show-item-context: true
    keyboard-shortcut: ["?",]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: file-play
        href: examples/lqr.qmd 
        text: Get started
      - icon: copy 
        href: tutorials.qmd 
        text: Examples
      - icon: braces
        href: api.qmd
        text: API
      - icon: patch-question 
        href: faq.qmd
        text: FAQ 
      - icon: book
        href: ressources.qmd 
      - about.qmd
    tools:
    - icon: gitlab
      menu:
        - text: "Source Code"
          href: https://kosinus.math.uni-magdeburg.de/mathopt/software/Corleone
        - text: "Report a bug"
          href: https://kosinus.math.uni-magdeburg.de/mathopt/software/corleone/-/issues/new
    - icon: house
      text: Mathopt Group
      href: https://www.mathopt.de

engines: ['julia']
julia:
  exeflags: ["--project=."]

execute:
  freeze: false

format:
  html:    
    respect-user-color-scheme: false
    theme:
      light: [cosmo, theme-light.css] 
      dark: [cosmo, theme-dark.css] 
    toc: true



