[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Corleone = "2751e0db-33e9-4374-b36d-b7219e1e6b40"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
