[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
