name: CI
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.group == 'Downstream' }}
    strategy:
      fail-fast: false
      matrix:
        group:
          - Corleone
          - CorleoneOED
        version:
          - '1.11'
          - 'lts'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v5
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ matrix.version }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ matrix.version }}-${{ env.cache-name }}-
            ${{ runner.os }}-test-${{ matrix.version }}-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: ${{ matrix.group }}
        env:
            GROUP: ${{ matrix.group }}
        shell: julia --color=yes --check-bounds=yes --depwarn=yes {0}
        run: |
          using Pkg
          const GROUP = get(ENV, "GROUP", "Core")

          function dev_subpkg(subpkgs::Vector{String})
            specs = [PackageSpec(path = "lib/$subpkg") for subpkg in subpkgs]
            Pkg.develop(specs)
          end

          if GROUP == "Corleone"
            Pkg.activate(".")
          else
            subpkg_path = "lib/${{ matrix.group }}"
            Pkg.activate(subpkg_path)
          end

          if VERSION < v"1.11"
            @info "Preparing env"
            if GROUP == "Corleone"
              @info "Testing Corleone"
            elseif GROUP == "CorleoneOED"
              dev_subpkg([".."])
            end
          end

          @info "Starting tests"
          Pkg.test()
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,lib/CorleoneOED/src
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info